#!/usr/bin/env python3
"""H4 analysis: Frequency gradient of reorganization strength.

For each patient and band, compute multiple reorganization-strength indices
from mean_VI (Variation of Information — lower = more similar):

  1. mean_all   – mean of all 6 pairwise distances
  2. mean_cross – mean of the 4 cross-type pairs (Pre↔TL, Pre↔TT, TL↔Post, TT↔Post)
  3. max_dist   – maximum distance among all 6 pairs
  4. spread     – max - min distance

Then assess whether a consistent frequency gradient exists across patients.

Produces (PDF only):
  data/figures/metric_exploration/h4_gradient/
    h4_reorganization_strength.pdf      — 4 metrics x curve per patient
    h4_band_ranking_heatmap.pdf         — rank of each band within each patient
    h4_task_effect.pdf                  — mean(cross) - mean(within) per band
    h4_ranking_agreement.pdf            — Kendall's W and pairwise rank correlations
"""
from __future__ import annotations

from pathlib import Path

from lrg_eegfc.utils.scripting import setup_script_env
ROOT = setup_script_env()

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
from scipy import stats

import argparse
from lrg_eegfc.config.paths import FIGURES_ROOT, REPORTS_ROOT

# ── Configuration ──────────────────────────────────────────────────────
_p = argparse.ArgumentParser(add_help=False)
_p.add_argument("--fc-method", default="imcoh_abs",
                choices=["msc", "corr", "imcoh_abs", "imcoh_sq"])
_FC_ARGS, _ = _p.parse_known_args()
FC_METHOD = _FC_ARGS.fc_method

# Per-fc-method CSV source:
#   - msc / corr: legacy partition_multiscale/results.csv (wide-format,
#     generated by the old partition_multiscale pipeline)
#   - imcoh_*: aggregated on-the-fly from data/reports/imcoh_vi/vi_raw_profiles.csv
#     (produced by scripts/01_compute/compute_imcoh_vi.py)
if FC_METHOD in ("imcoh_abs", "imcoh_sq"):
    CSV = REPORTS_ROOT / "imcoh_vi" / "vi_raw_profiles.csv"
    _CSV_KIND = "long"
else:
    CSV = FIGURES_ROOT / "metric_exploration" / "partition_multiscale" / "results.csv"
    _CSV_KIND = "wide"

OUTDIR = FIGURES_ROOT / "metric_exploration" / "h4_gradient" / FC_METHOD
OUTDIR.mkdir(parents=True, exist_ok=True)

from lrg_eegfc.config.const import PATIENTS_4PHASE
PATIENTS = PATIENTS_4PHASE
BANDS = ["delta", "theta", "alpha", "beta", "low_gamma", "high_gamma"]
BAND_LABELS = {
    "delta": r"$\delta$",
    "theta": r"$\theta$",
    "alpha": r"$\alpha$",
    "beta": r"$\beta$",
    "low_gamma": r"$\gamma_l$",
    "high_gamma": r"$\gamma_h$",
}
BAND_LABELS_PLAIN = {
    "delta": "delta",
    "theta": "theta",
    "alpha": "alpha",
    "beta": "beta",
    "low_gamma": "low_gamma",
    "high_gamma": "high_gamma",
}

PAT_COLORS = {
    "Pat_02": "#E91E63",
    "Pat_03": "#2196F3",
    "Pat_05": "#4CAF50",
    "Pat_08": "#FF9800",
}
PAT_MARKERS = {"Pat_02": "o", "Pat_03": "s", "Pat_05": "D", "Pat_08": "^"}

CROSS_PAIRS = [
    "rest_pre-task_learn", "rest_pre-task_test",
    "task_learn-rest_post", "task_test-rest_post",
]
WITHIN_PAIRS = ["rest_pre-rest_post", "task_learn-task_test"]

# ── Load data ──────────────────────────────────────────────────────────
if _CSV_KIND == "long":
    # vi_raw_profiles.csv: one row per (patient, band, phase_a, phase_b, k).
    # Aggregate to the wide-style per-(patient, band, pair) row expected by
    # the rest of this script, keeping mean_VI (averaged over k) and pair_type.
    long_df = pd.read_csv(CSV)
    long_df = long_df[long_df.patient.isin(PATIENTS)].copy()
    # pair_type is already present (within/cross); mean over k per pair
    df = (
        long_df.groupby(["patient", "band", "pair", "pair_type"], as_index=False)
               .agg(mean_VI=("vi", "mean"))
    )
else:
    df = pd.read_csv(CSV)
    df = df[df.patient.isin(PATIENTS)].copy()

print(f"H4 analysis for fc_method={FC_METHOD!r} "
      f"({_CSV_KIND}-format CSV from {CSV})")

# ── Compute reorganization strength per (patient, band) ───────────────
records = []
for pat in PATIENTS:
    for band in BANDS:
        sub = df[(df.patient == pat) & (df.band == band)]
        all_vi = sub["mean_VI"].values
        cross_vi = sub[sub.pair_type == "cross"]["mean_VI"].values
        within_vi = sub[sub.pair_type == "within"]["mean_VI"].values

        records.append({
            "patient": pat,
            "band": band,
            "mean_all": np.mean(all_vi),
            "mean_cross": np.mean(cross_vi),
            "mean_within": np.mean(within_vi),
            "max_dist": np.max(all_vi),
            "spread": np.max(all_vi) - np.min(all_vi),
            "task_effect": np.mean(cross_vi) - np.mean(within_vi),
        })

rs = pd.DataFrame(records)

# ── Print summary table ───────────────────────────────────────────────
print("=" * 80)
print("Reorganization strength summary (mean_VI, higher = more reorganization)")
print("=" * 80)
for metric in ["mean_all", "mean_cross", "max_dist", "spread", "task_effect"]:
    print(f"\n--- {metric} ---")
    pivot = rs.pivot(index="band", columns="patient", values=metric)
    pivot = pivot.reindex(BANDS)
    pivot["mean"] = pivot.mean(axis=1)
    print(pivot.round(4).to_string())

# ══════════════════════════════════════════════════════════════════════
# Figure 1: Reorganization strength vs frequency band (4 metrics)
# ══════════════════════════════════════════════════════════════════════
metrics = {
    "mean_all": "Mean of all 6 pairwise distances",
    "mean_cross": "Mean of 4 cross-type distances",
    "max_dist": "Max distance",
    "spread": "Spread (max - min)",
}

fig, axes = plt.subplots(2, 2, figsize=(14, 10), sharex=True)
axes = axes.ravel()
x = np.arange(len(BANDS))

for idx, (metric, title) in enumerate(metrics.items()):
    ax = axes[idx]

    # Per-patient lines
    for pat in PATIENTS:
        vals = rs[rs.patient == pat].set_index("band").reindex(BANDS)[metric].values
        ax.plot(x, vals, marker=PAT_MARKERS[pat], color=PAT_COLORS[pat],
                label=pat, linewidth=1.8, markersize=7, zorder=3)

    # Group mean with shading
    group_vals = np.array([
        rs[rs.band == b][metric].values for b in BANDS
    ])  # shape: (n_bands, n_patients)
    mean_line = group_vals.mean(axis=1)
    std_line = group_vals.std(axis=1)
    ax.plot(x, mean_line, color="black", linewidth=2.5, linestyle="--",
            label="Group mean", zorder=4)
    ax.fill_between(x, mean_line - std_line, mean_line + std_line,
                     color="black", alpha=0.1, zorder=1)

    ax.set_title(title, fontsize=12, fontweight="bold")
    ax.set_ylabel("mean_VI (distance)", fontsize=10)
    ax.set_xticks(x)
    ax.set_xticklabels([BAND_LABELS[b] for b in BANDS], fontsize=11)
    ax.grid(True, alpha=0.3)

    if idx == 0:
        ax.legend(fontsize=8, loc="best")

fig.suptitle("H4: Frequency Gradient of Reorganization Strength",
             fontsize=14, fontweight="bold", y=1.01)
fig.tight_layout()
fig.savefig(OUTDIR / "h4_reorganization_strength.pdf", bbox_inches="tight", dpi=150)
plt.close(fig)
print(f"\nSaved: {OUTDIR / 'h4_reorganization_strength.pdf'}")


# ══════════════════════════════════════════════════════════════════════
# Figure 2: Band ranking heatmap
# ══════════════════════════════════════════════════════════════════════
# Rank bands within each patient (for mean_cross metric)
# Rank 1 = highest reorganization
rank_records = []
for pat in PATIENTS:
    sub = rs[rs.patient == pat].set_index("band").reindex(BANDS)
    for metric in ["mean_all", "mean_cross"]:
        ranks = sub[metric].rank(ascending=False)  # 1 = highest
        for band in BANDS:
            rank_records.append({
                "patient": pat,
                "band": band,
                "metric": metric,
                "rank": ranks[band],
            })

rank_df = pd.DataFrame(rank_records)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for idx, metric in enumerate(["mean_all", "mean_cross"]):
    ax = axes[idx]
    sub = rank_df[rank_df.metric == metric]
    pivot = sub.pivot(index="band", columns="patient", values="rank")
    pivot = pivot.reindex(BANDS)[PATIENTS]

    im = ax.imshow(pivot.values, cmap="RdYlGn", aspect="auto",
                   vmin=1, vmax=6)
    ax.set_xticks(range(len(PATIENTS)))
    ax.set_xticklabels(PATIENTS, fontsize=9)
    ax.set_yticks(range(len(BANDS)))
    ax.set_yticklabels([BAND_LABELS[b] for b in BANDS], fontsize=11)

    # Annotate cells with rank
    for i in range(len(BANDS)):
        for j in range(len(PATIENTS)):
            val = pivot.values[i, j]
            ax.text(j, i, f"{val:.0f}", ha="center", va="center",
                    fontsize=12, fontweight="bold",
                    color="white" if val <= 2 or val >= 5 else "black")

    ax.set_title(f"Band ranking ({metric})\n(1 = most reorganization)",
                 fontsize=11, fontweight="bold")

fig.colorbar(im, ax=axes, shrink=0.8, label="Rank (1 = highest reorganization)")
fig.suptitle("H4: Do Patients Agree on Which Bands Reorganize Most?",
             fontsize=13, fontweight="bold", y=1.03)
fig.tight_layout()
fig.savefig(OUTDIR / "h4_band_ranking_heatmap.pdf", bbox_inches="tight", dpi=150)
plt.close(fig)
print(f"Saved: {OUTDIR / 'h4_band_ranking_heatmap.pdf'}")


# ══════════════════════════════════════════════════════════════════════
# Figure 3: Task effect = mean(cross) - mean(within)
# ══════════════════════════════════════════════════════════════════════
fig, ax = plt.subplots(figsize=(10, 6))

for pat in PATIENTS:
    vals = rs[rs.patient == pat].set_index("band").reindex(BANDS)["task_effect"].values
    ax.plot(x, vals, marker=PAT_MARKERS[pat], color=PAT_COLORS[pat],
            label=pat, linewidth=1.8, markersize=7, zorder=3)

# Group mean
group_vals = np.array([
    rs[rs.band == b]["task_effect"].values for b in BANDS
])
mean_line = group_vals.mean(axis=1)
std_line = group_vals.std(axis=1)
ax.plot(x, mean_line, color="black", linewidth=2.5, linestyle="--",
        label="Group mean", zorder=4)
ax.fill_between(x, mean_line - std_line, mean_line + std_line,
                 color="black", alpha=0.1, zorder=1)

ax.axhline(0, color="gray", linewidth=0.8, linestyle=":")
ax.set_xlabel("Frequency band", fontsize=11)
ax.set_ylabel("Task effect: mean(cross) - mean(within)", fontsize=11)
ax.set_title("H4: Task-Induced Disruption Across Frequency Bands",
             fontsize=13, fontweight="bold")
ax.set_xticks(x)
ax.set_xticklabels([BAND_LABELS[b] for b in BANDS], fontsize=11)
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3)

fig.tight_layout()
fig.savefig(OUTDIR / "h4_task_effect.pdf", bbox_inches="tight", dpi=150)
plt.close(fig)
print(f"Saved: {OUTDIR / 'h4_task_effect.pdf'}")


# ══════════════════════════════════════════════════════════════════════
# Figure 4: Ranking agreement — Kendall's W and pairwise correlations
# ══════════════════════════════════════════════════════════════════════

# Build rank matrix: patients x bands
rank_matrix = {}
for pat in PATIENTS:
    sub = rs[rs.patient == pat].set_index("band").reindex(BANDS)
    rank_matrix[pat] = sub["mean_cross"].rank(ascending=False).values

rank_mat = np.array([rank_matrix[p] for p in PATIENTS])  # (n_patients, n_bands)

# Kendall's W (coefficient of concordance)
n_judges = rank_mat.shape[0]  # patients
n_items = rank_mat.shape[1]   # bands
rank_sums = rank_mat.sum(axis=0)
mean_rank_sum = rank_sums.mean()
S = np.sum((rank_sums - mean_rank_sum) ** 2)
W = 12 * S / (n_judges**2 * (n_items**3 - n_items))

# Friedman test (chi-squared approximation)
chi2_friedman = n_judges * (n_items - 1) * W
p_friedman = 1 - stats.chi2.cdf(chi2_friedman, df=n_items - 1)

# Pairwise Spearman correlations between patients
from itertools import combinations
spearman_records = []
for p1, p2 in combinations(PATIENTS, 2):
    r, p_val = stats.spearmanr(rank_matrix[p1], rank_matrix[p2])
    spearman_records.append({"patient_1": p1, "patient_2": p2, "rho": r, "p": p_val})
spearman_df = pd.DataFrame(spearman_records)

print("\n" + "=" * 80)
print("Ranking agreement analysis (mean_cross)")
print("=" * 80)
print(f"\nKendall's W = {W:.4f}")
print(f"Friedman chi2({n_items - 1}) = {chi2_friedman:.4f}, p = {p_friedman:.6f}")
print(f"\nInterpretation of W:")
print(f"  W < 0.3 : weak agreement")
print(f"  0.3-0.5 : moderate agreement")
print(f"  0.5-0.7 : good agreement")
print(f"  W > 0.7 : strong agreement")
print(f"  -> W = {W:.4f} => {'weak' if W < 0.3 else 'moderate' if W < 0.5 else 'good' if W < 0.7 else 'strong'} agreement")
print(f"\nPairwise Spearman rank correlations:")
print(spearman_df.to_string(index=False))

# Also compute for mean_all
rank_matrix_all = {}
for pat in PATIENTS:
    sub = rs[rs.patient == pat].set_index("band").reindex(BANDS)
    rank_matrix_all[pat] = sub["mean_all"].rank(ascending=False).values

rank_mat_all = np.array([rank_matrix_all[p] for p in PATIENTS])
rank_sums_all = rank_mat_all.sum(axis=0)
mean_rank_sum_all = rank_sums_all.mean()
S_all = np.sum((rank_sums_all - mean_rank_sum_all) ** 2)
W_all = 12 * S_all / (n_judges**2 * (n_items**3 - n_items))

print(f"\nKendall's W (mean_all) = {W_all:.4f}")


# --- Figure 4: Combined ranking agreement visualization ---
fig, axes = plt.subplots(1, 3, figsize=(18, 6),
                          gridspec_kw={"width_ratios": [3, 2, 2]})

# Panel A: Rank profiles overlaid
ax = axes[0]
x_bands = np.arange(len(BANDS))
for pat in PATIENTS:
    ax.plot(x_bands, rank_matrix[pat], marker=PAT_MARKERS[pat],
            color=PAT_COLORS[pat], label=pat, linewidth=1.8, markersize=8)

# Median rank
median_rank = np.median(rank_mat, axis=0)
ax.plot(x_bands, median_rank, color="black", linewidth=2.5, linestyle="--",
        label="Median rank", zorder=4)

ax.set_xticks(x_bands)
ax.set_xticklabels([BAND_LABELS[b] for b in BANDS], fontsize=11)
ax.set_ylabel("Rank (1 = most reorganization)", fontsize=10)
ax.set_title("A) Band ranking per patient\n(mean_cross metric)",
             fontsize=11, fontweight="bold")
ax.set_ylim(0.5, 6.5)
ax.invert_yaxis()
ax.legend(fontsize=8)
ax.grid(True, alpha=0.3)

# Panel B: Spearman correlation matrix
ax = axes[1]
n_pat = len(PATIENTS)
corr_mat = np.ones((n_pat, n_pat))
for rec in spearman_records:
    i = PATIENTS.index(rec["patient_1"])
    j = PATIENTS.index(rec["patient_2"])
    corr_mat[i, j] = rec["rho"]
    corr_mat[j, i] = rec["rho"]

im = ax.imshow(corr_mat, cmap="RdBu_r", vmin=-1, vmax=1, aspect="equal")
ax.set_xticks(range(n_pat))
ax.set_xticklabels(PATIENTS, fontsize=9, rotation=45, ha="right")
ax.set_yticks(range(n_pat))
ax.set_yticklabels(PATIENTS, fontsize=9)
for i in range(n_pat):
    for j in range(n_pat):
        color = "white" if abs(corr_mat[i, j]) > 0.6 else "black"
        ax.text(j, i, f"{corr_mat[i, j]:.2f}", ha="center", va="center",
                fontsize=11, fontweight="bold", color=color)
ax.set_title("B) Pairwise Spearman\nrank correlations",
             fontsize=11, fontweight="bold")
plt.colorbar(im, ax=ax, shrink=0.8)

# Panel C: Summary statistics text
ax = axes[2]
ax.axis("off")
text_lines = [
    f"Kendall's W (concordance)",
    f"  mean_cross: W = {W:.3f}",
    f"  mean_all:   W = {W_all:.3f}",
    "",
    f"Friedman test (mean_cross):",
    f"  chi2({n_items-1}) = {chi2_friedman:.2f}",
    f"  p = {p_friedman:.4f}",
    "",
    f"Interpretation:",
    f"  W = {W:.3f} -> {'weak' if W < 0.3 else 'moderate' if W < 0.5 else 'good' if W < 0.7 else 'strong'}",
    f"  agreement",
    "",
    "Spearman rho range:",
    f"  [{spearman_df['rho'].min():.3f}, {spearman_df['rho'].max():.3f}]",
    f"  mean = {spearman_df['rho'].mean():.3f}",
]
ax.text(0.05, 0.95, "\n".join(text_lines), transform=ax.transAxes,
        fontsize=11, verticalalignment="top", fontfamily="monospace",
        bbox=dict(boxstyle="round,pad=0.5", facecolor="lightyellow", alpha=0.8))
ax.set_title("C) Agreement statistics",
             fontsize=11, fontweight="bold")

fig.suptitle("H4: Ranking Agreement Across Patients",
             fontsize=13, fontweight="bold", y=1.02)
fig.tight_layout()
fig.savefig(OUTDIR / "h4_ranking_agreement.pdf", bbox_inches="tight", dpi=150)
plt.close(fig)
print(f"Saved: {OUTDIR / 'h4_ranking_agreement.pdf'}")


# ══════════════════════════════════════════════════════════════════════
# Print final summary for report
# ══════════════════════════════════════════════════════════════════════
print("\n" + "=" * 80)
print("FINAL REPORT SUMMARY")
print("=" * 80)

# Consensus ranking (by median rank across patients, using mean_cross)
consensus = pd.DataFrame({
    "band": BANDS,
    "median_rank": np.median(rank_mat, axis=0),
    "mean_rank": np.mean(rank_mat, axis=0),
    "mean_cross_avg": [rs[rs.band == b]["mean_cross"].mean() for b in BANDS],
    "mean_cross_std": [rs[rs.band == b]["mean_cross"].std() for b in BANDS],
})
consensus = consensus.sort_values("mean_rank")
print("\nConsensus band ranking (by mean_cross, averaged across patients):")
print(consensus.to_string(index=False))

# Per-patient top-3
print("\nPer-patient top-3 bands (most reorganization by mean_cross):")
for pat in PATIENTS:
    sub = rs[rs.patient == pat].sort_values("mean_cross", ascending=False)
    top3 = sub.head(3)["band"].tolist()
    print(f"  {pat}: {' > '.join(top3)}")

# Task effect summary
print("\nTask effect (mean(cross) - mean(within)) averaged across patients:")
for band in BANDS:
    vals = rs[rs.band == band]["task_effect"].values
    print(f"  {band:12s}: {vals.mean():+.4f} (std={vals.std():.4f})")

# Individual patient rankings printed side by side
print("\nFull rankings per patient (1 = most reorganization):")
rank_pivot = pd.DataFrame(rank_matrix, index=BANDS)
rank_pivot.index.name = "band"
print(rank_pivot.to_string())
