#!/usr/bin/env python3
"""audit_110 — localization of the β inference-specific persistent trace.

WHERE does the inference-MARK accumulate on the cortex? The consolidation arc
(audit_103) found β consolidates an INFERENCE-specific component beyond encoding
(``T_infspec·e`` p=0.0068, β-only; α = encoding-only). The standard trace's
per-pair reorganization over-accumulates in ORBITOFRONTAL CORTEX (audit_83/92,
R=1000, BH q≈0.01). This asks the matching question for the inference-mark,
reusing the audit_83 matched-strength localization machinery VERBATIM — same
rank concordance (``concordance``), same per-system per-patient-demeaned endpoint
aggregation (``unit_means_from_s``), same canonical cophenetic (``_canon_cophenet``),
same strength-preserving null — but feeding it the arc's encoding / inference
per-pair vectors instead of the standard trace.

Framing (LOCKED, feedback_localization_is_overexpression_not_container): a
localization is an OVEREXPRESSION/ACCUMULATION hotspot on a trace DISTRIBUTED
across the whole network — never an exclusive container, never "absent
elsewhere". M_obs is per-patient DEMEANED → every number is concentration ABOVE
the distributed baseline.

Scope + 5-point preamble:
``.agents/guides/task-persistence-investigation/2026-06-18_inference-mark-localization.md``.

Targets (per-pair concordance vectors; c_ij>0 = sign-consistent persistence)
----------------------------------------------------------------------------
Canonical cophenetic D_x per phase. Differentials:
  g = D_taskTest − D_preA       (inference-online / STANDARD task change)
  e = D_taskLearn − D_preA      (ENCODING)
  f = D_taskTest − D_taskLearn  (INFERENCE-specific)
  p = D_restPost − D_preB       (PERSISTENT)
  standard       : concordance(g, p)            → reproduces OFC (CROSS-CHECK)
  encoding       : concordance(e, p)            → where memorising accumulates
  inference_raw  : concordance(f, p)            → inference, NOT controlling enc
  inference_pe   : concordance_partial(f, p|e)  → inference CONTROLLING encoding
                                                  = the β inference-MARK (HEADLINE)

Surrogate: canonical ``matched_strength_surrogate_lrg`` ensemble (seed 20260511),
phases incl ``task_learn`` (generated by audit_103 --null at R=200). R via --R
(R=1000 task_learn not yet cached → would need generation first).

Output
------
data/audit/inference_localization/inference_mark{suffix}_{epi}.csv
  one row per (band, target, granularity, unit); matched_strength_p +
  bh_q_system (BH across the 9 systems within band×target). suffix encodes
  shaft-collapse / R like audit_83.
"""
from __future__ import annotations

import argparse
import sys

import numpy as np
import pandas as pd
from scipy.stats import rankdata, spearmanr

from lrg_eegfc.utils.scripting import setup_script_env

ROOT = setup_script_env()

from lrg_eegfc.utils.metrics.hypothesis import bh_fdr
from lrg_eegfc.utils.io.regions import load_channel_regions
from lrg_eegfc.utils.metrics.node_localization import epi_keep_mask, shaft_of
from lrg_eegfc.utils.surrogate import (
    cophenetic_condensed_from_eigs, surrogate_cache_path,
)

# Reuse the EXACT audit_83 localizer primitives + the audit_63 phase loader
# (import, no fork). load_phase_fc is the function the surrogate eigs were
# generated from, so observed and surrogate share an FC source.
sys.path.insert(0, str(ROOT / "scripts" / "01_compute" / "audit"))
from audit_63_split_baseline_surrogate import (  # type: ignore
    ensure_half_fcs, load_phase_fc,
)
from audit_83_localization_matched_strength import (  # type: ignore
    concordance, unit_means_from_s, _canon_cophenet,
    GRANULARITIES, DROP, PARACORE,
)

COHORT = ["Pat_02", "Pat_03", "Pat_05", "Pat_06", "Pat_07",
          "Pat_08", "Pat_10", "Pat_13", "Pat_14", "Pat_15"]
TARGET_BANDS = ["beta", "alpha", "low_gamma"]   # arc trace bands
PHASES5 = ("rest_pre_A", "rest_pre_B", "task_learn", "task_test", "rest_post")
TARGETS = ("standard", "encoding", "inference_raw", "inference_pe")
SWAP, SEED = 20, 20260511
OUT_ROOT = ROOT / "data/audit/inference_localization"

# audit_83 canonical localization output, for the standard-target cross-check.
A83_CSV = ROOT / "data/audit/localization_atlas/matched_strength_R1000_include.csv"


# ---------------------------------------------------------------------------
# Per-pair statistics
# ---------------------------------------------------------------------------
def _rc(x: np.ndarray) -> np.ndarray:
    """Centered ranks: rank(x) − (n+1)/2."""
    return rankdata(x) - (x.size + 1) / 2.0


def concordance_partial(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> np.ndarray:
    """Per-pair contribution to the FIRST-ORDER PARTIAL Spearman ρ(a,b|c).

    Residualize centered-rank(a) and centered-rank(b) on centered-rank(c) (OLS
    slope = Σ r_x·r_c / Σ r_c²), return the elementwise product of the residuals.
    Its normalized sum = residual-form partial Spearman. Same operation on
    observed and surrogate, so the matched-strength null is UNCHANGED — only the
    observed statistic differs from the standard ``concordance``.
    """
    ra, rb, rc = _rc(a), _rc(b), _rc(c)
    rc2 = float(np.dot(rc, rc))
    if rc2 == 0.0:
        return ra * rb
    resid_a = ra - (np.dot(ra, rc) / rc2) * rc
    resid_b = rb - (np.dot(rb, rc) / rc2) * rc
    return resid_a * resid_b


def _partial_rho_formula(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> float:
    """audit_103 first-order partial Spearman (formula form), for cross-check."""
    rab = spearmanr(a, b).correlation
    rac = spearmanr(a, c).correlation
    rbc = spearmanr(b, c).correlation
    denom = np.sqrt(max(0.0, (1 - rac**2) * (1 - rbc**2)))
    return (rab - rac * rbc) / denom if denom > 0 else np.nan


def _targets_from_D(D: dict) -> dict:
    """Per-pair concordance for all four targets, from a phase→cophenetic dict
    (works for observed canonical cophenetics and per-realization surrogates)."""
    g = D["task_test"] - D["rest_pre_A"]
    e = D["task_learn"] - D["rest_pre_A"]
    f = D["task_test"] - D["task_learn"]
    p = D["rest_post"] - D["rest_pre_B"]
    return {
        "standard":      concordance(g, p),
        "encoding":      concordance(e, p),
        "inference_raw": concordance(f, p),
        "inference_pe":  concordance_partial(f, p, e),
        "_diffs": {"g": g, "e": e, "f": f, "p": p},
    }


# ---------------------------------------------------------------------------
# Observed + surrogate
# ---------------------------------------------------------------------------
def obs_targets(pat: str, band: str):
    """Observed per-pair concordance for all targets, canonical cophenetic."""
    D = {ph: _canon_cophenet(load_phase_fc(pat, ph, band)) for ph in PHASES5}
    t = _targets_from_D(D)
    # recover N from condensed length L = N(N-1)/2 → N = (1+sqrt(1+8L))/2
    N = int((1 + np.sqrt(1 + 8 * D["task_test"].size)) / 2)
    iu = np.triu_indices(N, k=1)
    return t, iu[0].astype(int), iu[1].astype(int)


def load_surrogate_cophenet5(pat: str, band: str, R: int):
    """Per-phase surrogate cophenetic condensed: dict phase -> list[R] of vec|None.
    Returns (None, missing_phase) if any phase cache is absent."""
    out = {}
    for ph in PHASES5:
        path = surrogate_cache_path(pat, band, ph, R, SWAP, SEED, "imcoh_abs")
        if not path.exists():
            return None, ph
        with np.load(path) as d:
            evals, evecs = d["eigvals"], d["eigvecs"]
        cond = []
        for r in range(evals.shape[0]):
            ev = evals[r]
            cond.append(None if not np.all(np.isfinite(ev))
                        else cophenetic_condensed_from_eigs(ev, evecs[r]))
        out[ph] = cond
    return out, None


# ---------------------------------------------------------------------------
# Per-band run
# ---------------------------------------------------------------------------
def run_band(band, epi_excl, R, shaft_collapse, verbose=True):
    rows = []
    obs_um = {t: {g: {} for g in GRANULARITIES} for t in TARGETS}
    surr_um = {t: {g: {} for g in GRANULARITIES} for t in TARGETS}
    strength_um = {g: {} for g in GRANULARITIES}
    xchecks = []  # (pat, ρstd_sum, ρstd_scipy, ρpe_resid, ρpe_formula, ρinf_sum, ρinf_scipy)

    for pat in COHORT:
        surco, miss = load_surrogate_cophenet5(pat, band, R)
        if surco is None:
            if verbose:
                print(f"  [skip] {pat} {band}: surrogate cache missing ({miss}, R={R})")
            continue
        try:
            t_obs, iu_i, iu_j = obs_targets(pat, band)
        except FileNotFoundError:
            if verbose:
                print(f"  [skip] {pat} {band}: phase FC / half missing")
            continue

        # --- cross-check: per-pair sums reproduce arc Spearman / partial ---
        d = t_obs["_diffs"]
        n = d["g"].size
        norm = n * (n * n - 1) / 12.0
        ra, rb, rc = _rc(d["f"]), _rc(d["p"]), _rc(d["e"])
        rc2 = float(np.dot(rc, rc))
        resid_a = ra - (np.dot(ra, rc) / rc2) * rc
        resid_b = rb - (np.dot(rb, rc) / rc2) * rc
        pe_norm = np.sqrt(float(np.dot(resid_a, resid_a)) * float(np.dot(resid_b, resid_b)))
        xchecks.append((
            pat,
            float(t_obs["standard"].sum() / norm),
            float(spearmanr(d["g"], d["p"]).correlation),
            float(t_obs["inference_pe"].sum() / pe_norm) if pe_norm > 0 else np.nan,
            _partial_rho_formula(d["f"], d["p"], d["e"]),
            float(t_obs["inference_raw"].sum() / norm),
            float(spearmanr(d["f"], d["p"]).correlation),
        ))

        rdf = load_channel_regions(pat)
        rdf["paracore"] = rdf["system"].map(
            lambda s: "paralimbic_core" if s in PARACORE
            else ("non_anatomical" if s == "non_anatomical" else "other_np"))
        keep = epi_keep_mask(rdf, pat) if epi_excl else None
        shaft_vec = (np.array([shaft_of(l) for l in rdf["label_raw"]])
                     if shaft_collapse else None)
        s_node = np.mean(np.vstack(
            [load_phase_fc(pat, ph, band).sum(axis=1)
             for ph in ("rest_pre", "task_test", "rest_post")]), axis=0)

        # precompute surrogate per-pair targets per realization (shared D_r)
        sr = []
        for r in range(R):
            Dr = {ph: surco[ph][r] for ph in PHASES5}
            sr.append(None if any(Dr[ph] is None for ph in PHASES5)
                      else _targets_from_D(Dr))

        for g in GRANULARITIES:
            uv = rdf[g].to_numpy().astype(str)
            om_t = {t: unit_means_from_s(t_obs[t], iu_i, iu_j, uv, keep,
                                         DROP[g], shaft_vec=shaft_vec)
                    for t in TARGETS}
            for t in TARGETS:
                for u, m in om_t[t].items():
                    obs_um[t][g].setdefault(u, {})[pat] = m
            per = {t: {u: [] for u in om_t[t]} for t in TARGETS}
            for r in range(R):
                if sr[r] is None:
                    continue
                for t in TARGETS:
                    sm = unit_means_from_s(sr[r][t], iu_i, iu_j, uv, keep,
                                           DROP[g], shaft_vec=shaft_vec)
                    for u in per[t]:
                        if u in sm:
                            per[t][u].append(sm[u])
            for t in TARGETS:
                for u in om_t[t]:
                    surr_um[t][g].setdefault(u, {})[pat] = np.array(per[t][u])
            # strength companion (target-independent)
            keepn = np.ones(len(uv), bool) if keep is None else keep
            sd = s_node - s_node[keepn].mean()
            for u in om_t["standard"]:
                sel = (uv == u) & keepn
                if sel.any():
                    strength_um[g].setdefault(u, {})[pat] = float(sd[sel].mean())

    # --- cross-check report ---
    if xchecks:
        xc = np.array([[c[1] - c[2], c[3] - c[4], c[5] - c[6]] for c in xchecks])
        print(f"  [xcheck {band}] max|Δ| standard(sum-vs-scipy)={np.nanmax(np.abs(xc[:,0])):.2e}"
              f"  inference_pe(resid-vs-formula)={np.nanmax(np.abs(xc[:,1])):.2e}"
              f"  inference_raw(sum-vs-scipy)={np.nanmax(np.abs(xc[:,2])):.2e}")

    # --- cohort verdict per (target, granularity, unit) ---
    for t in TARGETS:
        for g in GRANULARITIES:
            sys_rows = []
            for u, pm in obs_um[t][g].items():
                samplers = sorted(pm)
                K = len(samplers)
                if K == 0:
                    continue
                M_obs = float(np.median([pm[p] for p in samplers]))
                arrs = [surr_um[t][g][u].get(p) for p in samplers]
                arrs = [a for a in arrs if a is not None and len(a) > 0]
                if not arrs:
                    continue
                Lmin = min(len(a) for a in arrs)
                Rmat = np.vstack([a[:Lmin] for a in arrs])
                M_surr = np.median(Rmat, axis=0)
                nval = M_surr.size
                p_ms = (1 + int(np.sum(M_surr >= M_obs))) / (nval + 1)
                strv = strength_um[g].get(u, {})
                str_med = (float(np.median([strv[p] for p in samplers if p in strv]))
                           if any(p in strv for p in samplers) else np.nan)
                row = {
                    "band": band, "epi": "exclude" if epi_excl else "include",
                    "shaft_collapse": bool(shaft_collapse), "target": t,
                    "granularity": g, "unit": u, "K_implanted": K, "M_obs": M_obs,
                    "surr_mean": float(np.mean(M_surr)),
                    "surr_median": float(np.median(M_surr)),
                    "matched_strength_p": p_ms, "n_surr": nval,
                    "strength_dev_median": str_med, "bh_q_system": np.nan,
                }
                rows.append(row)
                if g == "system":
                    sys_rows.append(row)
            if sys_rows:
                qs = bh_fdr([r["matched_strength_p"] for r in sys_rows])
                for r, q in zip(sys_rows, qs):
                    r["bh_q_system"] = q
            if verbose and g == "system":
                for r in sorted(sys_rows, key=lambda r: r["matched_strength_p"]):
                    star = "*" if r["bh_q_system"] < 0.05 else " "
                    print(f"  {band:9s} {t:13s} {r['unit']:16s} "
                          f"M_obs={r['M_obs']:+.3e} MS_p={r['matched_strength_p']:.3f} "
                          f"q={r['bh_q_system']:.3f}{star} (K={r['K_implanted']}, "
                          f"str={r['strength_dev_median']:+.2f})")
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--band", default=None)
    ap.add_argument("--epi-mode", choices=["include", "exclude"], default=None)
    ap.add_argument("--shaft-collapse", action="store_true")
    ap.add_argument("--R", type=int, default=200)
    args = ap.parse_args()
    bands = [args.band] if args.band else TARGET_BANDS
    epis = ([args.epi_mode == "exclude"] if args.epi_mode else [False, True])
    suffix = ("_shaftcollapsed" if args.shaft_collapse else "") \
        + (f"_R{args.R}" if args.R != 200 else "")
    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    print("[audit_110] pre-flight: ensure rsPre half FCs cached")
    for pat in COHORT:
        ensure_half_fcs(pat, bands)

    for epi_excl in epis:
        etag = "exclude" if epi_excl else "include"
        tag = f"epi-{etag}" + (" SHAFT-COLLAPSED" if args.shaft_collapse else "")
        print(f"\n==== inference-mark localization : {tag}  (R={args.R}) ====")
        allrows = []
        for band in bands:
            allrows += run_band(band, epi_excl, args.R,
                                shaft_collapse=args.shaft_collapse)
        out = OUT_ROOT / f"inference_mark{suffix}_{etag}.csv"
        pd.DataFrame(allrows).to_csv(out, index=False)
        print(f"  -> {out} ({len(allrows)} rows)")

    # standard-target cross-check vs canonical audit_83 OFC localization
    if A83_CSV.exists() and not args.shaft_collapse:
        ref = pd.read_csv(A83_CSV)
        ref = ref[(ref.granularity == "system") & (ref.unit == "OFC")
                  & (ref.band == "beta")]
        if not ref.empty:
            print(f"\n[CROSS-CHECK] audit_83 β/system/OFC standard M_obs = "
                  f"{float(ref.iloc[0]['M_obs']):+.3e} "
                  f"(compare to this run's standard β/system/OFC M_obs above)")


if __name__ == "__main__":
    main()
