"""Workflow orchestration subpackage."""

from .core import BandComputationResult, compute_band_connectivity
from .substrate import (
    Substrate,
    CANONICAL,
    CANONICAL_PHASES,
    CANONICAL_SCALES,
    canonical_scale_grid,
    canonical_graph,
    canonical_graph_ensemble,
    canonical_eig,
    canonical_phase_graphs,
    canonical_phase_eigs,
    canonical_structure,
)
from .corr import CorrResult, compute_corr_matrix, load_corr_matrix, get_corr_cache_path, compute_corr_for_patient
from .msc import MSCResult, compute_msc_matrix, load_msc_matrix, get_msc_cache_path, compute_msc_for_patient
from .lrg import LRGResult, compute_lrg_analysis, load_lrg_result, get_lrg_cache_path, compute_lrg_for_patient
from .cleaning import (
    CleanedCorrResult,
    clean_correlation_matrix_full,
    load_cleaned_corr_matrix,
    get_cleaned_corr_cache_path,
    compute_cleaned_corr_for_patient,
)
from .time_windows import (
    DEFAULT_WINDOW_OVERLAP,
    DEFAULT_WINDOW_MIN_SEC,
    DEFAULT_WINDOW_CYCLES,
    DEFAULT_CORR_WINDOWS_CACHE_ROOT,
    DEFAULT_MSC_WINDOWS_CACHE_ROOT,
    DEFAULT_LRG_WINDOWS_CACHE_ROOT,
    DEFAULT_CORR_WINDOWS_DEV_CACHE_ROOT,
    DEFAULT_MSC_WINDOWS_DEV_CACHE_ROOT,
    DEFAULT_LRG_WINDOWS_DEV_CACHE_ROOT,
    build_window_run_id,
    get_window_cache_dir,
    get_lrg_window_cache_dir,
    suggest_window_sec,
    compute_window_params,
    generate_window_indices,
)

__all__ = [
    "BandComputationResult",
    "compute_band_connectivity",
    # the locked substrate -- one entry point for the analysed graph
    "Substrate",
    "CANONICAL",
    "CANONICAL_PHASES",
    "CANONICAL_SCALES",
    "canonical_scale_grid",
    "canonical_graph",
    "canonical_graph_ensemble",
    "canonical_eig",
    "canonical_phase_graphs",
    "canonical_phase_eigs",
    "canonical_structure",
    "CorrResult",
    "compute_corr_matrix",
    "load_corr_matrix",
    "get_corr_cache_path",
    "compute_corr_for_patient",
    "MSCResult",
    "compute_msc_matrix",
    "load_msc_matrix",
    "get_msc_cache_path",
    "compute_msc_for_patient",
    "LRGResult",
    "compute_lrg_analysis",
    "load_lrg_result",
    "get_lrg_cache_path",
    "compute_lrg_for_patient",
    "CleanedCorrResult",
    "clean_correlation_matrix_full",
    "load_cleaned_corr_matrix",
    "get_cleaned_corr_cache_path",
    "compute_cleaned_corr_for_patient",
    "DEFAULT_WINDOW_OVERLAP",
    "DEFAULT_WINDOW_MIN_SEC",
    "DEFAULT_WINDOW_CYCLES",
    "DEFAULT_CORR_WINDOWS_CACHE_ROOT",
    "DEFAULT_MSC_WINDOWS_CACHE_ROOT",
    "DEFAULT_LRG_WINDOWS_CACHE_ROOT",
    "DEFAULT_CORR_WINDOWS_DEV_CACHE_ROOT",
    "DEFAULT_MSC_WINDOWS_DEV_CACHE_ROOT",
    "DEFAULT_LRG_WINDOWS_DEV_CACHE_ROOT",
    "build_window_run_id",
    "get_window_cache_dir",
    "get_lrg_window_cache_dir",
    "suggest_window_sec",
    "compute_window_params",
    "generate_window_indices",
]
